
// Source port: attached DocumentScreens.kt / QuotationScreens.kt / ReturnScreens.kt.
const SD=globalThis.JasviDomain, SC=globalThis.JasviSource;
const sourceRoutes=SC.routes;
function runUi(task){Promise.resolve().then(task).catch(e=>jasviToast(e.message,'error'));}
function sourceField(id,label,value='',type='text',options){return `<label class="field"><span>${jasviEsc(label)}</span>${options?`<select name="${id}">${[...new Set(['',...options,value].filter(v=>v!=null))].map(v=>`<option value="${jasviEsc(v)}" ${v===value?'selected':''}>${jasviEsc(v||'Select…')}</option>`).join('')}</select>`:type==='textarea'?`<textarea name="${id}" rows="2">${jasviEsc(value??'')}</textarea>`:`<input name="${id}" type="${type}" ${type==='number'?'step="any"':''} value="${jasviEsc(value??'')}">`}</label>`;}
function sourceModal(title){const w=document.createElement('div');w.className='modal-backdrop source-modal';w.innerHTML=`<section class="dialog" role="dialog" aria-modal="true" aria-label="${jasviEsc(title)}" tabindex="-1"><h2>${jasviEsc(title)}</h2><form><div class="dialog-body source-body"></div><p class="error-text source-error" role="alert"></p><div class="dialog-actions"><button type="button" class="secondary source-close">Close</button><button type="submit" class="primary source-save">Save</button></div></form></section>`;document.body.append(w);const previous=document.activeElement,form=w.querySelector('form');let busy=false;const close=()=>{if(busy)return;w.remove();previous?.focus?.();};w.querySelector('.source-close').onclick=close;w.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();close();}if(e.key==='Tab'){const els=[...w.querySelectorAll('input,select,textarea,button,[tabindex]')].filter(e=>!e.disabled&&e.getAttribute('tabindex')!=='-1');if(!els.length)return;if(e.shiftKey&&document.activeElement===els[0]){e.preventDefault();els.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===els.at(-1)){e.preventDefault();els[0].focus();}}});w.querySelector('section').focus();return {w,form,body:w.querySelector('.source-body'),error:msg=>{w.querySelector('.source-error').textContent=msg;},busy:v=>{busy=v;w.querySelector('.source-save').disabled=v;w.querySelector('.source-close').disabled=v;},close};}
async function selectSourceRecord(kind,chosen){const party=kind!=='ITEM',type=kind;const m=sourceModal(party?'Select '+(type==='CUSTOMER'?'Customer':'Supplier'):'Select Item');m.w.querySelector('.source-save').remove();m.body.innerHTML=`${sourceField('query','Search','')}<button type="button" class="secondary source-search">Search</button><div class="source-results"></div>`;let request=0;const search=async()=>{const seq=++request;const q=m.form.elements.query.value.trim();const url=party?sourceRoutes.PARTIES_SEARCH+'?'+new URLSearchParams({type,q,limit:'100'}):sourceRoutes.ITEMS_SEARCH+'?'+new URLSearchParams({q,limit:'100'});m.error('');try{const rows=await jasviApi(url);if(seq!==request||!m.w.isConnected)return;const out=m.w.querySelector('.source-results');out.replaceChildren();for(const r of rows){const b=document.createElement('button');b.type='button';b.className='source-result';b.textContent=party?`${r.partyCode} • ${r.name}`:`${r.itemCode} • ${r.description}`;b.onclick=()=>{chosen(r);m.close();};out.append(b);}if(!rows.length)out.textContent='No matching records.';}catch(e){m.error(e.message);}};m.w.querySelector('.source-search').onclick=search;m.form.onsubmit=e=>{e.preventDefault();search();};await search();}
function editSourceLine(sales,current,onSave){const m=sourceModal('Item Line');let l={...SC.models.DocumentLine,...current};m.body.innerHTML=`<button type="button" class="secondary source-pick">Select Item</button><p class="source-item-name">${jasviEsc(l.itemCode||'Select an item')}</p><div class="source-grid">${sourceField('quantity','Quantity',l.quantity,'number')}${sourceField('rate','Rate',l.rate,'number')}${sourceField('discountPercent','Discount %',l.discountPercent,'number')}${sourceField('gstPercent','GST %',l.gstPercent,'number')}${sourceField('itemRemarks','Remarks',l.itemRemarks)}</div>`;m.w.querySelector('.source-pick').onclick=()=>runUi(()=>selectSourceRecord('ITEM',item=>{l={...l,itemCode:item.itemCode,itemDescription:item.description,itemUnit:item.unit,itemHsn:item.hsn};m.w.querySelector('.source-item-name').textContent=`${item.itemCode} • ${item.description}`;for(const [k,v] of Object.entries({rate:sales?item.sellingPrice:item.purchasePrice,gstPercent:item.gst,discountPercent:item.discountPercent})){m.form.elements[k].value=v||0;}}));m.form.onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(m.form));const line=SD.line({...l,...v});const error=SD.validateLines([line]);if(error)return m.error(error);onSave(line);m.close();};}
function editSourceCharge(types,current,onSave){const m=sourceModal('Additional Charge');const c={...SC.models.DocumentCharge,...current};m.body.innerHTML=sourceField('chargeType','Charge Type',c.chargeType,'text',types)+sourceField('amount','Amount',c.amount,'number')+`<label class="check"><input name="taxable" type="checkbox" ${c.taxable?'checked':''}>Taxable</label>`+sourceField('gstPercent','GST %',c.gstPercent,'number');m.form.onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(m.form));onSave({chargeType:v.chargeType,amount:Number(v.amount),taxable:!!v.taxable,gstPercent:Number(v.gstPercent)});m.close();};}
async function openDocumentEditor(type,current=null,duplicate=false){
 const sales=type==='SALE',module=sales?'SALES':'PURCHASE',create=!current||duplicate;if(!jasviCan(module,create?'CREATE':'EDIT'))throw Error('You do not have permission for this action.');if(!create&&!SD.policy(type,current).canEdit)throw Error('Cancelled or deleted documents cannot be edited.');
 const m=sourceModal(create?'Create '+(sales?'Sale':'Purchase'):'Edit '+current.invoiceNo);m.body.innerHTML=jasviLoading('Loading document fields…');m.busy(true);
 try{
  const boot=await jasviApi(sourceRoutes.SALES_ENTRY_BOOTSTRAP);let d={...structuredClone(SC.models[sales?'SaleRecord':'PurchaseRecord']),...structuredClone(current||{})};
  if(duplicate){d={...SC.models.PurchaseRecord,...d,id:null,invoiceNo:'',rowVersion:0,paidAmount:0,paymentStatus:null,documentStatus:null,createdAt:null,createdBy:jasviState.user?.username,emailSent:false,attachmentPath:null};}
  d.invoiceDate=d.invoiceDate||jasviToday();d.paymentTerms=d.paymentTerms||(boot.paymentTerms||[]).find(x=>x.toLowerCase()==='15 days')||boot.paymentTerms?.[0]||'';d.gstType=d.gstType||boot.gstTypes?.[0]||'';d.dueDate=d.dueDate||SD.dueDate(d.invoiceDate,d.paymentTerms);
  if(sales)d.invoiceType=d.invoiceType||'TAX INVOICE';else Object.assign(d,{currency:d.currency||'INR - Indian Rupee',warehouse:d.warehouse||'Main Warehouse',gstTreatment:d.gstTreatment||'Business Purchase',discountType:d.discountType||'Item Level',deliveryDate:d.deliveryDate||d.dueDate});
  let party=d[sales?'customer':'supplier'],lines=d.lines.map(SD.line),charges=d.charges.map(c=>({...c}));let preview=d.invoiceNo;if(create)preview=(await jasviApi(sales?sourceRoutes.SALES_NEXT:sourceRoutes.PURCHASES_NEXT)).value;
  const field=(k,label,type='text',opts)=>sourceField(k,label,d[k],type,opts);
  m.body.innerHTML=`${preview?`<p>Document No: <strong>${jasviEsc(preview)}</strong></p>`:''}<button type="button" class="secondary source-party">Select ${sales?'Customer':'Supplier'}</button><p class="source-party-name">${jasviEsc(party?.name||'Select a party')}</p><div class="source-grid">${field('invoiceDate',sales?'Invoice Date':'Purchase Date','date')}${field('paymentTerms','Payment Term','text',boot.paymentTerms||[])}${field('dueDate','Due Date','date')}${field('gstType','GST Type','text',boot.gstTypes||[])}${sales?field('invoiceType','Invoice Type','text',['TAX INVOICE','BILL OF SUPPLY','EXPORT INVOICE'])+field('salesperson','Salesperson'):''}${field('referenceNo','Reference No')}${field('orderNo','Order / PO No')}${field('poDate','PO Date','date')}</div><h3>Addresses</h3><div class="source-grid">${field('billingGstin','Billing GSTIN')}${field('billingAddress','Billing Address','textarea')}</div><label class="check"><input type="checkbox" name="sameAsBilling" ${d.sameAsBilling?'checked':''}>Delivery same as billing</label><div class="source-grid source-delivery">${field('deliveryGstin','Delivery GSTIN')}${field('deliveryAddress','Delivery Address','textarea')}</div><h3>Items</h3><div class="source-lines"></div><button type="button" class="secondary source-add-line">＋ Add Item</button><h3>Additional Charges</h3><div class="source-charges"></div><button type="button" class="secondary source-add-charge">＋ Add Charge</button><details><summary>Transport & Notes</summary><div class="source-grid">${field('transporter','Transporter','text',(boot.transporters||[]).filter(x=>x.active).map(x=>x.lookupValue))}${field('transporterGstin','Transporter GSTIN')}${field('vehicleNumber','Vehicle No')}${field('contactPerson','Contact Person')}${field('contactPersonMobile','Contact Mobile')}${sales?field('transportNote','Transport Note'):''}${field('notes','Notes','textarea')}</div></details><h3>Totals</h3><div class="source-totals"></div><p class="muted">The ERP recalculates the final amount when saved.</p>`;
  const repaint=()=>{m.w.querySelector('.source-lines').innerHTML=lines.map((l,i)=>`<div class="source-line"><div><b>${jasviEsc(l.itemCode)}</b><span>${jasviEsc(l.itemDescription)} • ${l.quantity} × ${l.rate} • GST ${l.gstPercent}%</span><strong>${jasviRupee(l.totalAmount)}</strong></div><button type="button" data-edit-line="${i}">✎ Edit</button><button type="button" data-remove-line="${i}">× Remove</button></div>`).join('')||'<p>No items yet.</p>';m.w.querySelector('.source-charges').innerHTML=charges.map((c,i)=>`<div class="source-line"><div>${jasviEsc(c.chargeType)} • ${jasviRupee(c.amount)} • GST ${c.gstPercent}%</div><button type="button" data-edit-charge="${i}">✎ Edit</button><button type="button" data-remove-charge="${i}">× Remove</button></div>`).join('');const t=SD.totals(lines,charges);m.w.querySelector('.source-totals').innerHTML=`<dl>${jasviDetailRows([['Gross',jasviRupee(t.gross)],['Discount',jasviRupee(t.discount)],['Taxable',jasviRupee(t.taxable)],['GST',jasviRupee(t.tax)],['Charges',jasviRupee(t.chargeTotal)],['Total',jasviRupee(t.total)]])}</dl>`;m.w.querySelectorAll('[data-edit-line]').forEach(b=>b.onclick=()=>editSourceLine(sales,lines[+b.dataset.editLine],l=>{lines[+b.dataset.editLine]=l;repaint();}));m.w.querySelectorAll('[data-remove-line]').forEach(b=>b.onclick=()=>{lines.splice(+b.dataset.removeLine,1);repaint();});m.w.querySelectorAll('[data-edit-charge]').forEach(b=>b.onclick=()=>editSourceCharge(boot.chargeTypes,charges[+b.dataset.editCharge],c=>{charges[+b.dataset.editCharge]=c;repaint();}));m.w.querySelectorAll('[data-remove-charge]').forEach(b=>b.onclick=()=>{charges.splice(+b.dataset.removeCharge,1);repaint();});};
  m.w.querySelector('.source-add-line').onclick=()=>editSourceLine(sales,null,l=>{lines.push(l);repaint();});m.w.querySelector('.source-add-charge').onclick=()=>{if(sales&&charges.length>=2)return m.error('A maximum of 2 additional charges is allowed.');editSourceCharge(boot.chargeTypes,null,c=>{charges.push(c);repaint();});};
  const syncAddress=()=>{m.w.querySelector('.source-delivery').hidden=m.form.elements.sameAsBilling.checked;};syncAddress();m.form.elements.sameAsBilling.onchange=syncAddress;
  m.w.querySelector('.source-party').onclick=()=>runUi(()=>selectSourceRecord(sales?'CUSTOMER':'SUPPLIER',p=>{party=p;m.w.querySelector('.source-party-name').textContent=p.name;for(const [k,v] of Object.entries({billingAddress:p.address,billingGstin:p.gstin,contactPerson:p.contactPerson,contactPersonMobile:p.phone}))m.form.elements[k].value=v||'';}));
  const updateDue=()=>{m.form.elements.dueDate.value=SD.dueDate(m.form.elements.invoiceDate.value,m.form.elements.paymentTerms.value);};m.form.elements.invoiceDate.onchange=updateDue;m.form.elements.paymentTerms.onchange=updateDue;m.form.elements.dueDate.readOnly=true;
  m.form.elements.transporter.onchange=()=>{m.form.elements.transporterGstin.value=boot.transporters?.find(x=>x.lookupValue===m.form.elements.transporter.value)?.description||'';};
  repaint();m.busy(false);
  m.form.onsubmit=async e=>{e.preventDefault();m.error('');const v=Object.fromEntries(new FormData(m.form)),same=!!v.sameAsBilling;const t=SD.totals(lines,charges);const dto={...d,...v,[sales?'customer':'supplier']:Object.fromEntries(Object.keys(SC.models.PartyRef).map(k=>[k,party?.[k]??SC.models.PartyRef[k]])),sameAsBilling:same,deliveryAddress:same?v.billingAddress:v.deliveryAddress,deliveryGstin:same?v.billingGstin:v.deliveryGstin,subtotal:t.taxable,discountAmount:t.discount,gstAmount:t.tax,totalAmount:t.total,quantity:lines.reduce((a,l)=>a+l.quantity,0),lines,charges};if(sales)dto.gstin=party?.gstin;else dto.deliveryDate=v.dueDate;const error=SD.validateDocument(type,dto);if(error)return m.error(error);if(!window.confirm(`${create?'Create':'Update'} this ${sales?'Sale':'Purchase'} in UAT for ${jasviRupee(t.total)}?`))return;m.busy(true);try{await jasviApi(sourceRoutes.HEALTH,{auth:false});const saved=await jasviApi(sales?sourceRoutes.SALES:sourceRoutes.PURCHASES,{method:create?'POST':'PUT',body:dto});m.busy(false);m.close();jasviToast(`Saved ${saved.invoiceNo} • ${jasviRupee(saved.totalAmount)}`);await (sales?jasviLoadSales():jasviLoadPurchases());jasviRenderApp();}catch(e){m.busy(false);m.error(e.message+' Your form is retained. If the save request timed out, check the register before trying again.');}};
 }catch(e){m.busy(false);m.error(e.message);m.w.querySelector('.source-save').disabled=true;}
}
async function openQuotationEditor(current=null){
 if(!jasviCan('QUOTATION',current?'EDIT':'CREATE'))throw Error('Quotation permission required.');const m=sourceModal(current?'Edit '+current.no:'Create Quotation');m.busy(true);m.body.innerHTML=jasviLoading();
 try{const sources=await jasviApi(sourceRoutes.QUOTATION_SOURCES);let party=null,lines=[];if(current){const parties=await jasviApi(sourceRoutes.PARTIES_SEARCH+'?'+new URLSearchParams({type:'CUSTOMER',q:current.customer,limit:'100'}));party=parties.find(p=>p.id===current.customerId);const qlines=await jasviApi(sourceRoutes.QUOTATIONS+'/'+current.id+'/lines');lines=qlines.map(l=>SD.line({itemCode:l.code,itemDescription:l.description,quantity:l.quantity,rate:l.rate,gstPercent:l.gst,discountPercent:l.discount}));}const date=current?.date||jasviToday();m.body.innerHTML=`<button type="button" class="secondary source-party">Select Customer</button><p class="source-party-name">${jasviEsc(party?.name||'Select customer')}</p><div class="source-grid">${sourceField('date','Quotation Date',date,'date')}${sourceField('valid','Valid Until',current?.valid||SD.dueDate(date,'15 Days'),'date')}${sourceField('followUp','Follow-up Date',current?.followUp,'date')}${sourceField('source','Quotation Source',current?.source||sources[0],'text',sources)}${sourceField('salesperson','Salesperson',current?.salesperson)}</div><h3>Items</h3><div class="source-lines"></div><button type="button" class="secondary source-add-line">＋ Add Item</button>${sourceField('remarks','Remarks',current?.remarks,'textarea')}<div class="source-totals"></div>`;
 const repaint=()=>{m.w.querySelector('.source-lines').innerHTML=lines.map((l,i)=>`<div class="source-line"><div><b>${jasviEsc(l.itemCode)}</b><span>${l.quantity} × ${l.rate} • ${jasviRupee(l.totalAmount)}</span></div><button type="button" data-edit="${i}">✎ Edit</button><button type="button" data-remove="${i}">× Remove</button></div>`).join('');m.w.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editSourceLine(true,lines[+b.dataset.edit],l=>{lines[+b.dataset.edit]=l;repaint();}));m.w.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{lines.splice(+b.dataset.remove,1);repaint();});m.w.querySelector('.source-totals').textContent='Total: '+jasviRupee(lines.reduce((s,l)=>s+l.totalAmount,0));};repaint();m.w.querySelector('.source-add-line').onclick=()=>editSourceLine(true,null,l=>{lines.push(l);repaint();});m.w.querySelector('.source-party').onclick=()=>runUi(()=>selectSourceRecord('CUSTOMER',p=>{party=p;m.w.querySelector('.source-party-name').textContent=p.name;}));m.busy(false);
 m.form.onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(m.form));let error=SD.validateLines(lines);if(!party?.id)error='Select customer.';if(!SD.validDate(v.date)||!SD.validDate(v.valid)||!v.source)error='Date, valid until and source are required.';if(error)return m.error(error);const total=SD.roundMoney(lines.reduce((s,l)=>s+l.totalAmount,0)),subtotal=SD.roundMoney(lines.reduce((s,l)=>{const gross=SD.roundMoney(l.quantity*l.rate);return s+SD.roundMoney(gross-SD.roundMoney(gross*l.discountPercent/100));},0));const dto={id:current?.id||null,...v,customerId:party.id,subtotal,discountAmount:SD.roundMoney(lines.reduce((s,l)=>s+l.discountAmount,0)),gstAmount:SD.roundMoney(Math.max(0,total-subtotal)),total,createdBy:current?.createdBy||jasviState.user?.username,lines:lines.map(l=>({code:l.itemCode,description:l.itemDescription,quantity:l.quantity,rate:l.rate,gst:l.gstPercent,discount:l.discountPercent,total:l.totalAmount}))};if(!window.confirm(`Save this quotation in UAT for ${jasviRupee(total)}?`))return;m.busy(true);try{await jasviApi(sourceRoutes.QUOTATIONS+(current?'/'+current.id:''),{method:current?'PUT':'POST',body:dto});m.busy(false);m.close();jasviToast('Quotation saved');await jasviLoadQuotes();jasviRenderApp();}catch(e){m.busy(false);m.error(e.message+' Check the register before retrying an uncertain save.');}};
 }catch(e){m.busy(false);m.error(e.message);m.w.querySelector('.source-save').disabled=true;}
}
async function createSourceReturn(type,record){const sales=type==='SALE',module=sales?'SALES':'PURCHASE';if(!jasviCan(module,'EDIT')||!SD.policy(type,record).canReturn)throw Error('Returns require an approved, fully paid source invoice.');const returnType=sales?'SALES RETURN':'PURCHASE RETURN';const previous=await jasviApi(sourceRoutes.RETURNS+'/returned?'+new URLSearchParams({type:returnType,invoice:record.invoiceNo}));const rows=SD.eligibleReturns(record.lines,previous);const m=sourceModal('Create '+returnType);m.body.innerHTML=`<p>${jasviEsc(record.invoiceNo)} • ${jasviEsc((record.customer||record.supplier)?.name)}</p>${sourceField('returnDate','Return Date',jasviToday(),'date')}<p>The ERP calculates the return amount from the original invoice.</p>`+rows.map((r,i)=>`<div class="source-line"><div><b>${jasviEsc(r.code)} • ${jasviEsc(r.description)}</b><span>Invoiced ${r.invoiced}; previously returned ${r.previouslyReturned}; eligible ${r.eligible}</span>${sourceField('qty'+i,'Return Quantity',0,'number')}${sourceField('reason'+i,'Reason','')}</div></div>`).join('');m.form.onsubmit=async e=>{e.preventDefault();const chosen=rows.map((r,i)=>({...r,quantity:Number(m.form.elements['qty'+i].value),reason:m.form.elements['reason'+i].value}));const error=SD.validateReturns(chosen);if(error)return m.error(error);if(!SD.validDate(m.form.elements.returnDate.value))return m.error('Select a valid return date.');if(!window.confirm('Create this pending return in UAT?'))return;m.busy(true);try{const saved=await jasviApi(sourceRoutes.RETURNS,{method:'POST',body:{type:returnType,invoiceNo:record.invoiceNo,partyId:(record.customer||record.supplier).id,returnDate:m.form.elements.returnDate.value,lines:chosen.filter(r=>r.quantity>0).map(r=>({code:r.code,quantity:r.quantity,amount:0,reason:r.reason}))}});m.busy(false);m.close();jasviToast('Created '+saved.returnNo+' • PENDING APPROVAL');}catch(e){m.busy(false);m.error(e.message+' Check returns before retrying an uncertain save.');}};}
