/* Browser translation of DocumentScreens.kt, ReturnScreens.kt and DseComponents.kt
   from the attached archive identified by source-provenance.json. */
(function(g){
'use strict';
const norm=v=>String(v??'').trim().toUpperCase();
const sum=xs=>xs.reduce((a,b)=>a+b,0);
const roundMoney=v=>{const n=v*100,f=Math.floor(n),fraction=n-f;return (fraction===0.5?(f%2===0?f:f+1):Math.round(n))/100;};
function line(l){const q=Number(l.quantity),r=Number(l.rate),d=Number(l.discountPercent),gst=Number(l.gstPercent);const gross=roundMoney(q*r),disc=roundMoney(gross*d/100),taxable=q*r*(1-d/100);return {...l,quantity:q,rate:r,discountPercent:d,gstPercent:gst,discountAmount:disc,totalAmount:taxable*(1+gst/100)};}
function totals(lines,charges=[]){const gross=roundMoney(sum(lines.map(l=>roundMoney(l.quantity*l.rate)))),discount=roundMoney(sum(lines.map(l=>roundMoney(roundMoney(l.quantity*l.rate)*l.discountPercent/100)))),taxable=roundMoney(sum(lines.map(l=>l.quantity*l.rate*(1-l.discountPercent/100)))),lineTax=roundMoney(sum(lines.map(l=>roundMoney(l.quantity*l.rate*(1-l.discountPercent/100)*l.gstPercent/100)))),base=roundMoney(sum(charges.map(c=>roundMoney(c.amount)))),tax=roundMoney(sum(charges.filter(c=>c.taxable).map(c=>roundMoney(c.amount*c.gstPercent/100))));return {gross,discount,taxable,tax:roundMoney(lineTax+tax),chargeTotal:roundMoney(base+tax),total:roundMoney(taxable+lineTax+base+tax)};}
function validDate(s){return /^\d{4}-\d{2}-\d{2}$/.test(s)&&Number.isFinite(Date.parse(s))&&new Date(s+'T00:00:00Z').toISOString().slice(0,10)===s;}
function dueDate(date,term){if(!validDate(date))return '';const d=new Date(date+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+Number(String(term).match(/\d+/)?.[0]||0));return d.toISOString().slice(0,10);}
function validateLines(lines){if(!lines.length)return 'Add items.';for(const l of lines){if(!l.itemCode||![l.quantity,l.rate,l.discountPercent,l.gstPercent].every(Number.isFinite)||l.quantity<=0||l.rate<0||l.discountPercent<0||l.discountPercent>100||l.gstPercent<0||l.gstPercent>100)return 'Correct invalid item quantities, rates, discounts or GST values.';}return '';}
function validateDocument(type,d){if(!validDate(d.invoiceDate))return 'Select a valid invoice date.';const party=type==='SALE'?d.customer:d.supplier;if(!party?.id)return 'Select '+(type==='SALE'?'customer.':'supplier.');if(!String(d.deliveryAddress||'').trim())return 'Enter delivery address.';if(!d.sameAsBilling&&norm(d.billingAddress)===norm(d.deliveryAddress)&&norm(d.billingGstin)===norm(d.deliveryGstin))return "Select 'Delivery same as billing' or update the delivery details.";const error=validateLines(d.lines);if(error)return error;if(type==='PURCHASE'&&(!d.paymentTerms||!d.gstType))return 'Select Payment Term and GST Type from Master Data.';const charges=d.charges||[];if(type==='SALE'&&charges.length>2)return 'A maximum of 2 additional charges is allowed.';const names=new Set();for(const c of charges){if(!norm(c.chargeType))return 'Select a charge type for every charge row.';if(!Number.isFinite(c.amount)||c.amount<=0)return 'Charge amount must be greater than zero.';if(names.has(norm(c.chargeType)))return 'The same charge type cannot be selected twice.';names.add(norm(c.chargeType));if(!Number.isFinite(c.gstPercent)||c.gstPercent<0||c.gstPercent>100)return 'Charge GST percent must be between 0 and 100.';if(!c.taxable&&c.gstPercent>0.0001)return 'Non-taxable charges cannot have a GST percent.';}return '';}
function policy(type,r){const st=norm(r.documentStatus),payment=norm(r.paymentStatus),active=!['CANCELLED','DELETED'].includes(st),approvalLocked=['PENDING APPROVAL','REJECTED'].includes(st),due=Math.max(0,r.totalAmount-r.paidAmount),fullyPaid=['PAID','SETTLED'].includes(payment)||r.paidAmount+0.009>=r.totalAmount,financiallyLocked=r.paidAmount>0.009||['PAID','SETTLED','PARTIAL'].some(s=>payment.includes(s));return {active,approvalLocked,due,canEdit:active,canPay:active&&!approvalLocked&&(type!=='PURCHASE'||st!=='DRAFT')&&due>0.005,canReturn:st==='APPROVED'&&fullyPaid&&!['RETURN PENDING','RETURN PARTIAL'].includes(payment),canCancel:active&&!financiallyLocked,canOutput:active&&!approvalLocked,pendingApproval:st==='PENDING APPROVAL'};}
function eligibleReturns(lines,previous){const grouped=new Map();for(const l of lines){const r=grouped.get(l.itemCode)||{code:l.itemCode,description:l.itemDescription||l.itemCode,invoiced:0};r.invoiced+=Number(l.quantity);grouped.set(l.itemCode,r);}return [...grouped.values()].map(r=>({...r,previouslyReturned:Math.min(Number(previous[r.code]||0),r.invoiced),eligible:Math.max(0,r.invoiced-Number(previous[r.code]||0))}));}
function validateReturns(rows){if(!rows.some(r=>Number(r.quantity)>0))return 'Select at least one return quantity.';if(rows.some(r=>!Number.isFinite(Number(r.quantity))||Number(r.quantity)<0||Number(r.quantity)>r.eligible+0.0001))return 'Return quantity must be between zero and the eligible quantity.';return '';}
g.JasviDomain=Object.freeze({line,totals,roundMoney,validDate,dueDate,validateLines,validateDocument,policy,eligibleReturns,validateReturns});
})(globalThis);
